############################################################
#
# web访问端口号  约定：8088
#
############################################################
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8  #编码格式
    accept-count: 1000 #最大的等待队列
    threads:
      min-spare: 100
      max: 800
    max-http-form-post-size: 0
  max-http-header-size: 4096  #单位B
  servlet:
    context-path: /seckill

############################################################
#
# 配置数据源信息
#
############################################################
spring:
  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
  datasource:                                           # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource          # 数据源类型：HikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver          # mysql驱动
    url: jdbc:mysql://localhost:3306/miaosha?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: root
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP     # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1 #连接的时候查询测试
    # Redis
  redis:
      # 启用哨兵模式以后无需直接连接 Redis，通过哨兵可以获得主从信息
    port: 6379
    host: localhost
    timeout: 3000 # 连接超时时间
      #password: # Redis 服务器密码
    database: 0
      # lettuce 连接池
    lettuce:
      pool:
        max-active: 50 # 最大连接数，默认 8
        max-idle: 50 # 最大空闲连接，默认 8
        min-idle: 20 # 最小空闲连接，默认 0
        max-wait: 1000 # 最大连接阻塞等待时间，单位毫秒，默认 -1
  servlet:
    multipart:
      max-file-size: 512000     # 文件上传大小限制为500kb
      max-request-size: 512000  # 请求大小限制为500kb
  #freemarker配置
  freemarker:
    cache: false  #关闭模板缓存，方便测试
    settings:
      template_update_delay: 0  #检查模板更新延迟时间，设置为0表示立即检查，如果时间大于0会有缓存不方便进行模板测试
    template-loader-path: classpath:/templates
    charset: UTF-8
    check-template-location: true
    suffix: .ftl
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request

############################################################
#
# mybatis 配置
#
############################################################
mybatis:
  type-aliases-package: com.xiaoliu.seckill.pojo          # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml      # mapper映射文件
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

############################################################
#
# mybatis mapper 配置
#
############################################################
# 通用 Mapper 配置
mapper:
  mappers: com.xiaoliu.seckill.dao.mapper.MyMapper
  not-empty: false    # 在进行数据库操作的的时候，判断表达式 username != null, 是否追加 username != ''
  identity: MYSQL
# 分页插件配置
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true

mq:
  nameserver:
    addr: 121.37.228.35:9876
  topicname: TopicShop

#静态页位置
htmlPath: D:/page/html
#htmlPath: /usr/local/server/web/html/web/items


#websocket配置
ws:
  port: 28082
  host: 0.0.0.0



